name: Build and Deploy Astro Site

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14  # Choose the Node.js version you need

      - name: Install Dependencies
        run: npm install  # or yarn install if you use yarn

      - name: Build Astro Site
        run: npm run build  # Replace with your build command

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # Replace with the directory where your built site is generated
          publish_branch: gh-pages
